name: fraser
favicon: null
layout_spectrum: 0.24995
typography_spectrum: 0
title: Just ramblings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#94b9dd'
    - '#446882'
    - '#f3d6aa'
    - '#271e19'
  brandStrength: 0.5
  lightness: 0.7995866411365569
  saturation: 0.617137455381453
  rhythmicContrast: 0.5
purpose: []
