name: fraser
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Fraser McCulloch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#334c00'
    - '#fafcf9'
    - '#ff0047'
    - '#ffc37f'
    - '#0db5ff'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
