name: fraser
favicon: null
layout_spectrum: 0.75275
typography_spectrum: 0.00229
title: Fraser McCulloch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0184a'
    - '#ffffff'
    - '#d73c66'
    - '#e88fa8'
    - '#df6283'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
