name: fraser
favicon: null
layout_spectrum: 0.75275
typography_spectrum: 0.00229
title: Fraser McCulloch
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2eb1ff'
    - '#fff100'
    - '#8cd698'
    - '#74ba81'
    - '#b3df65'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
